# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fbb195089db7607f05706de7e8e9b4f96bae8a29c64a2edef991fee0185a3729c82e1bb61d9a926de69c3bea9f144483e4b7b468c8c4e42f8b3583eb97038c8

test:
  secret_key_base: b2ff8cd13f6eb8ff6aa2c09e10ae4e6e043822f7eefde0573b8cb4c006873f6470aa3d136bd52247fcedd44c9780b4dff236f954bd479f46ebd928cceca69038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
